name: WeaponsPlugin
main: ostkaka34.WeaponsPlugin.WeaponsPlugin
depend: [OstEconomyPlugin]
version: 0
commands:
   buyammo:
      description: Let you buy ammo.
      usage: /buyammo
      permission: weaponsplugin.buyammo